environment:
  matrix:
    - PYTHON_VERSION: "3.4"

platform:
  - x64

matrix:
  fast_finish: false

install:
  - set COMPILER_PATH=C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1\\mingw64\\bin\\
  - set PATH=%COMPILER_PATH%;C:\msys64\usr\bin\;C:\Miniconda-x64\Scripts;%PATH%
  - bash -c "echo $PATH"
  - bash -c "which gcc"
  - bash -c "which gfortran"
  - bash -c "which make"
  - bash -c "which libtool"
  - conda config --set always_yes yes --set changeps1 no
  - conda create -q --name python%PYTHON_VERSION% python=%PYTHON_VERSION% 
  - activate python%PYTHON_VERSION%
  - bash -c "cd /c/projects/climt/; python setup.py build"
    #  - conda update -q conda
    #  - pip install -r requirements_dev.txt
    #  - python.exe setup.py install

build: off

#test_script:
#  - pip install -U tox
#  - tox

#after_test:
  # This step builds your wheels.
  # - python.exe setup.py bdist_wheel

#artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  #- path: dist\*.whl

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.
