dist: trusty
sudo: required
language: python
python: 3.5
env:
- TOXENV=cov
- TOXENV=flake8
- TOXENV=py35
- TOXENV=py34
- TOXENV=py27
before_install:
- sudo apt-get install gfortran
install:
- pip install -r requirements_dev.txt
- pip install -U tox
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  server: https://test.pypi.org/legacy/
  user: Twine
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: false
    repo: CliMT/climt
    condition: "$TOXENV == py27"
notifications:
  email:
    recipients:
    - joy.monteiro@misu.su.se
    - mcgibbon@uw.edu
